# ======================================================================
#  CoralEmbed.cmake — Self-contained binary embedding module
#
#  Usage:
#    target_embed_files(<target>
#        [<INTERFACE|PUBLIC|PRIVATE>
#        <OUTPUT_HEADER>
#        <NAMESPACE>
#        ]...)
#    )
#
#  Example:
#    coral_embed(
#        MyApp
#        "${CMAKE_SOURCE_DIR}/assets/DefaultLit.bin"
#        "${CMAKE_BINARY_DIR}/generated/Coral/Shaders/DefaultLit.hpp"
#        "Coral::Shaders"
#    )
#
# ======================================================================

function(target_embed_files TARGET_NAME VISIBILITY)

set(_options)
set(_oneValueArgs NAMESPACE OUTPUT_DIR FILE_SET)
set(_multiValueArgs FILES BASE_DIRS)

cmake_parse_arguments("" "${_options}" "${_oneValueArgs}" "${_multiValueArgs}" ${ARGN} )

foreach(_input_file ${_FILES})

    get_filename_component(_input_file "${_input_file}" ABSOLUTE)
    if(NOT EXISTS "${_input_file}")
        message(FATAL_ERROR "target_embed_files: Input file does not exist: ${_input_file}")
    endif()

    get_filename_component(_name "${_input_file}" NAME)
    string(REGEX REPLACE "\\." "_" _name "${_name}")

    ###########################################################################
    # Setup the output file
    ###########################################################################

    set(_output_file "${_OUTPUT_DIR}/${_name}.hpp")

    ###########################################################################
    # Construct include guard at configure time
    ###########################################################################

    set(_include_guard "${_NAMESPACE}_${_name}_HPP")
    string(TOUPPER "${_include_guard}" _include_guard)
    string(REPLACE "::" "_" _include_guard "${_include_guard}")
    string(REGEX REPLACE "[^A-Z0-9]" "_" _include_guard "${_include_guard}")

    ###########################################################################
    # Create the template header file
    ###########################################################################

    set(_embed_template "
// Generated by coral_embed
#ifndef ${_include_guard}
#define ${_include_guard}

#include <array>

namespace ${_NAMESPACE}
{

constexpr std::array<uint8_t, \${_length}> ${_name} = {
    \${_bytes}
};

} // namespace ${_NAMESPACE}

#endif // ${_include_guard}
")

    ###########################################################################
    # Create the per-file embed script and write it to the binary directory at 
    # configuration time
    ###########################################################################

    set(_embed_script "
file(READ \"${_input_file}\" _data HEX)
string(LENGTH \"\${_data}\" _length)
string(REGEX REPLACE \"([0-9A-Fa-f][0-9A-Fa-f])\" \"0x\\\\1,\" _bytes \"\${_data}\")

set(_template \"${_embed_template}\")

file(WRITE  \"${_output_file}\" \"\${_template}\")
")

    string(MD5 _script_name ${_input_file})
    # Write the embedded script into the build directory
    set(_script_file "${CMAKE_CURRENT_BINARY_DIR}/target_embed_files/${_script_name}.cmake")
    file(WRITE "${_script_file}" "${_embed_script}")

    ###########################################################################
    # 1. Add a custom command to invoke the embed script at build-time to
    # regenerate the header file when the input file changes
    ###########################################################################

    add_custom_command(
        OUTPUT ${_output_file}
        COMMAND ${CMAKE_COMMAND}
            -DINPUT="${_input_file}"
            -DOUTPUT="${_output_file}"
            -P "${_script_file}"
        DEPENDS "${_input_file}" ${_script_file}
        COMMENT "Embedding binary ${_input_file} → ${_output_file}"
        VERBATIM)

    ###########################################################################
    # 2. Invoke the embed script at configuration time to generate the first 
    # version of the header (so target_sources can see it)
    ###########################################################################

    execute_process(
        COMMAND ${CMAKE_COMMAND}
            -DINPUT="${_input_file}"
            -DOUTPUT="${_output_file}"
            -P "${_script_file}"
        RESULT_VARIABLE _res
    )

    if(NOT _res EQUAL 0)
        message(FATAL_ERROR "coral_embed: Failed to generate header at configure time.")
    endif()

    ###########################################################################
    # 3. Add the generated header file to the target via target_sources
    ###########################################################################

    target_sources(${TARGET_NAME} ${VISIBILITY}
        FILE_SET ${_FILE_SET}
        TYPE HEADERS
        BASE_DIRS ${_BASE_DIRS}
        FILES ${_output_file})

endforeach()

endfunction()
